import type { FormSchema } from "@/lib/shared/types/forms.types";

import { ROUTES } from "@/lib/shared/constants/routes";

/**
 * Canonical DS-11 schema (edition 04-2025, OMB 1405-0004).
 *
 * GENERATED by scripts/build-ds11-schema.mjs from schemas/ds11-raw-fields.json.
 * Edit the section and label table in that script and re-run, rather than
 * editing this file, so every rect stays sourced from the real AcroForm
 * widget instead of being hand-authored.
 *
 * All 99 widgets live on PDF pages 5 and 6; pages 1-4 are instructions. The
 * bottom of page 5 and everything under "FOR ISSUING OFFICE ONLY" on page 6
 * are completed in person by the acceptance agent and carry no fields.
 *
 * Option ids are the AcroForm export values verbatim, so the overlay, the
 * preview stamper and the backend filler need no translation table.
 *
 * "Name of Applicant 2" and "Applicant DOB 2" — the repeated header on page 6
 * — are deliberately absent: the filler mirrors them from the page 5 values
 * rather than asking for the same details twice.
 */
export const DS_11_SCHEMA: FormSchema = {
  id: "ds-11",
  label: "Form DS-11",
  pdfUrl: ROUTES.STATIC.DS11_BLANK_PDF,
  pageCount: 6,
  sections: [
    {
      id: "document",
      title: "Document Selection",
      description: "Which passport product you are paying for.",
      fields: [
        {
          id: "doc_type",
          label: "Select document(s) for which you are submitting fees",
          type: "radio",
          required: true,
          pdfRef: "Selection",
          rect: { page: 5, x: 89.02, y: 710.51, w: 259.5, h: 10.93 },
          options: [
            {
              id: "Book",
              label: "U.S. Passport Book",
              rect: { page: 5, x: 89.02, y: 710.51, w: 12.56, h: 10.93 },
            },
            {
              id: "Card",
              label: "U.S. Passport Card",
              rect: { page: 5, x: 212.73, y: 710.51, w: 12.56, h: 10.93 },
            },
            {
              id: "Both",
              label: "Both",
              rect: { page: 5, x: 335.96, y: 710.51, w: 12.56, h: 10.93 },
            },
          ],
          helpText:
            "The passport card is not valid for international air travel.",
        },
        {
          id: "book_size",
          label: "Book size",
          type: "radio",
          required: false,
          pdfRef: "Regular or Large Book",
          rect: { page: 5, x: 112.58, y: 691.53, w: 141.71, h: 10.8 },
          options: [
            {
              id: "Regular",
              label: "Regular Book (Standard)",
              rect: { page: 5, x: 112.58, y: 691.53, w: 10.8, h: 10.8 },
            },
            {
              id: "Large",
              label: "Large Book (Non-Standard)",
              rect: { page: 5, x: 243.49, y: 691.53, w: 10.8, h: 10.8 },
            },
          ],
          helpText:
            "The large book is for frequent international travelers who need more visa pages.",
        },
      ],
    },

    {
      id: "applicant",
      title: "1-7. Your Details",
      description: "Name, date and place of birth, and identifying numbers.",
      fields: [
        {
          id: "last_name",
          label: "1. Last Name",
          type: "text",
          required: true,
          pdfRef: "Applicant Last Name",
          rect: { page: 5, x: 70.95, y: 645.53, w: 322.91, h: 20.2 },
          maxLength: 21,
        },
        {
          id: "first_name",
          label: "First Name",
          type: "text",
          required: true,
          pdfRef: "Applicant First Name",
          rect: { page: 5, x: 71.65, y: 612.89, w: 260.68, h: 20.86 },
          maxLength: 17,
        },
        {
          id: "middle_name",
          label: "Middle Name",
          type: "text",
          required: false,
          pdfRef: "Applicant Middle Name",
          rect: { page: 5, x: 338.05, y: 612.28, w: 246.78, h: 21.51 },
          maxLength: 16,
        },
        {
          id: "dob_month",
          label: "2. Date of Birth - Month (MM)",
          type: "text",
          required: true,
          pdfRef: "Applicant DOB M",
          rect: { page: 5, x: 69.38, y: 579.53, w: 33.49, h: 22 },
          maxLength: 2,
        },
        {
          id: "dob_day",
          label: "Date of Birth - Day (DD)",
          type: "text",
          required: true,
          pdfRef: "Applicant DOB D",
          rect: { page: 5, x: 105.66, y: 580.71, w: 31.53, h: 22 },
          maxLength: 2,
        },
        {
          id: "dob_year",
          label: "Date of Birth - Year (YYYY)",
          type: "text",
          required: true,
          pdfRef: "Applicant DOB Y",
          rect: { page: 5, x: 139.04, y: 580.71, w: 61.64, h: 22 },
          maxLength: 4,
        },
        {
          id: "sex",
          label: "3. Sex",
          type: "radio",
          required: true,
          pdfRef: "Gender",
          rect: { page: 5, x: 242.21, y: 579.66, w: 29.77, h: 12.11 },
          options: [
            {
              id: "M",
              label: "M",
              rect: { page: 5, x: 242.21, y: 579.66, w: 12.76, h: 12.11 },
            },
            {
              id: "F",
              label: "F",
              rect: { page: 5, x: 259.22, y: 579.66, w: 12.76, h: 12.11 },
            },
          ],
        },
        {
          id: "place_of_birth",
          label: "4. Place of Birth",
          type: "text",
          required: true,
          pdfRef: "Applicant Place of Birth",
          rect: { page: 5, x: 308.53, y: 579.95, w: 277.05, h: 21.51 },
          maxLength: 18,
          helpText:
            "City and state if in the U.S., or city and country as it is presently known.",
        },
        {
          id: "ssn_1",
          label: "5. Social Security Number - first 3",
          type: "text",
          required: true,
          pdfRef: "Applicant SSN 1",
          rect: { page: 5, x: 70.96, y: 546.02, w: 46.58, h: 22 },
          maxLength: 3,
        },
        {
          id: "ssn_2",
          label: "Social Security Number - middle 2",
          type: "text",
          required: true,
          pdfRef: "Applicant SSN 2",
          rect: { page: 5, x: 120.58, y: 546.06, w: 31.53, h: 22 },
          maxLength: 2,
        },
        {
          id: "ssn_3",
          label: "Social Security Number - last 4",
          type: "text",
          required: true,
          pdfRef: "Applicant SSN 3",
          rect: { page: 5, x: 154.5, y: 544.9, w: 62.29, h: 22 },
          maxLength: 4,
        },
        {
          id: "a_number",
          label: "6. USCIS Registration A-Number (if applicable)",
          type: "text",
          required: false,
          pdfRef: "Alien Number",
          rect: { page: 5, x: 239.99, y: 546.19, w: 146.76, h: 22 },
          maxLength: 9,
          helpText:
            "Digits only - the form already prints the leading A- for you.",
        },
        {
          id: "email",
          label: "7. Email",
          type: "text",
          required: false,
          pdfRef: "Applicant Email",
          rect: { page: 5, x: 397.38, y: 544.32, w: 187.62, h: 22.32 },
          helpText:
            "Used to check application status at passportstatus.state.gov.",
        },
      ],
    },

    {
      id: "mailing",
      title: "8-9. Mailing Address and Phone",
      description: "Where the State Department will send your passport.",
      fields: [
        {
          id: "mailing_street",
          label: "8. Mailing Address Line 1",
          type: "text",
          required: true,
          pdfRef: "Applicant Address Street",
          rect: { page: 5, x: 26.18, y: 514.97, w: 554.79, h: 20.38 },
          maxLength: 36,
          helpText:
            "Street/RFD#, P.O. Box, or URB. Also include apartment, suite, etc.",
        },
        {
          id: "mailing_line2",
          label: "Address Line 2",
          type: "text",
          required: false,
          pdfRef: "Address Line 2",
          rect: { page: 5, x: 26.84, y: 481.43, w: 553.79, h: 22.82 },
          maxLength: 36,
          helpText:
            "If the applicant is a child, write In Care Of the parent. Example: In Care Of - Jane Doe.",
        },
        {
          id: "mailing_city",
          label: "City",
          type: "text",
          required: true,
          pdfRef: "Applicant Address City",
          rect: { page: 5, x: 27.05, y: 448.07, w: 207.16, h: 21.56 },
          maxLength: 14,
        },
        {
          id: "mailing_state",
          label: "State",
          type: "text",
          required: true,
          pdfRef: "Applicant Address State",
          rect: { page: 5, x: 256.04, y: 448.84, w: 33.71, h: 20.68 },
          maxLength: 2,
        },
        {
          id: "mailing_zip",
          label: "Zip Code",
          type: "text",
          required: true,
          pdfRef: "Applicant Address Zip Code",
          rect: { page: 5, x: 295.06, y: 449.17, w: 87.09, h: 21.73 },
          maxLength: 6,
        },
        {
          id: "mailing_country",
          label: "Country (if outside the United States)",
          type: "text",
          required: false,
          pdfRef: "Applicant Address Country",
          rect: { page: 5, x: 396.4, y: 449.17, w: 184.35, h: 21.07 },
          maxLength: 12,
        },
        {
          id: "phone_1",
          label: "9. Primary Phone - area code",
          type: "text",
          required: false,
          pdfRef: "Applicant Phone 1",
          rect: { page: 5, x: 26.35, y: 417.76, w: 45.32, h: 20.16 },
          maxLength: 3,
        },
        {
          id: "phone_2",
          label: "Primary Phone - prefix",
          type: "text",
          required: false,
          pdfRef: "Applicant Phone 2",
          rect: { page: 5, x: 73.23, y: 417.53, w: 43.22, h: 20.16 },
          maxLength: 3,
        },
        {
          id: "phone_3",
          label: "Primary Phone - line number",
          type: "text",
          required: false,
          pdfRef: "Applicant Phone 3",
          rect: { page: 5, x: 118.7, y: 417.97, w: 57.67, h: 20.16 },
          maxLength: 4,
        },
        {
          id: "other_name_a",
          label: "Other name you have used (A)",
          type: "text",
          required: false,
          pdfRef: "List all other name you have used",
          rect: { page: 5, x: 190.96, y: 417.82, w: 187.77, h: 19.93 },
          maxLength: 13,
          helpText:
            "Birth name, maiden name, previous marriage, or legal name change.",
        },
        {
          id: "other_name_b",
          label: "Other name you have used (B)",
          type: "text",
          required: false,
          pdfRef: "List all other names you have used",
          rect: { page: 5, x: 396.96, y: 417.8, w: 185.32, h: 21.51 },
          maxLength: 13,
        },
      ],
    },

    {
      id: "page2_header",
      title: "Page 2 Header",
      description:
        "Repeated at the top of page 2. Left blank, these are filled from your details on page 1.",
      fields: [
        {
          id: "applicant_name_page2",
          label: "Name of Applicant (Last, First, & Middle)",
          type: "text",
          required: false,
          pdfRef: "Name of Applicant 2",
          rect: { page: 6, x: 27.62, y: 737.47, w: 414.61, h: 21.11 },
        },
        {
          id: "applicant_dob_page2",
          label: "Date of Birth (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Applicant DOB 2",
          rect: { page: 6, x: 455.67, y: 738.07, w: 130.36, h: 21.35 },
        },
      ],
    },

    {
      id: "parents",
      title: "10. Parental Information",
      description: "Both parents, as named at their own birth.",
      fields: [
        {
          id: "parent1_first_middle",
          label: "Parent 1 - First and Middle Name (at parent's birth)",
          type: "text",
          required: false,
          pdfRef: "Parent 1 FM Name",
          rect: { page: 6, x: 27.29, y: 698.05, w: 309.88, h: 21.11 },
        },
        {
          id: "parent1_last",
          label: "Parent 1 - Last Name (at parent's birth)",
          type: "text",
          required: false,
          pdfRef: "Parent 1 Last Name",
          rect: { page: 6, x: 340.82, y: 696.35, w: 245.74, h: 22.42 },
        },
        {
          id: "parent1_dob",
          label: "Parent 1 - Date of Birth (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Parent 1 DOB",
          rect: { page: 6, x: 27.76, y: 663.84, w: 130.36, h: 22 },
        },
        {
          id: "parent1_birthplace",
          label: "Parent 1 - Place of Birth",
          type: "text",
          required: false,
          pdfRef: "Parent 1 Place of Birth",
          rect: { page: 6, x: 169.57, y: 663.72, w: 308.22, h: 22 },
        },
        {
          id: "parent1_sex",
          label: "Parent 1 - Sex",
          type: "radio",
          required: false,
          pdfRef: "Parent 1 Gender",
          rect: { page: 6, x: 494.19, y: 665.66, w: 8.64, h: 18.14 },
          options: [
            {
              id: "M",
              label: "M",
              rect: { page: 6, x: 494.19, y: 675.16, w: 8.64, h: 8.64 },
            },
            {
              id: "F",
              label: "F",
              rect: { page: 6, x: 494.19, y: 665.66, w: 8.64, h: 8.97 },
            },
          ],
        },
        {
          id: "parent1_us_citizen",
          label: "Parent 1 - U.S. Citizen?",
          type: "radio",
          required: false,
          pdfRef: "Parent 1 US Citizen",
          rect: { page: 6, x: 529.88, y: 663.07, w: 8.85, h: 19.77 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 530.09, y: 674.2, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 529.88, y: 663.07, w: 8.64, h: 8.84 },
            },
          ],
        },
        {
          id: "parent2_first_middle",
          label: "Parent 2 - First and Middle Name (at parent's birth)",
          type: "text",
          required: false,
          pdfRef: "Parent 2 FM Name",
          rect: { page: 6, x: 27.68, y: 633.7, w: 309.42, h: 21.11 },
        },
        {
          id: "parent2_last",
          label: "Parent 2 - Last Name (at parent's birth)",
          type: "text",
          required: false,
          pdfRef: "Parent 2 Last Name",
          rect: { page: 6, x: 340.86, y: 633.84, w: 244.19, h: 21.18 },
        },
        {
          id: "parent2_dob",
          label: "Parent 2 - Date of Birth (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Parent 2 DOB",
          rect: { page: 6, x: 27.4, y: 600.58, w: 130.36, h: 22 },
        },
        {
          id: "parent2_birthplace",
          label: "Parent 2 - Place of Birth",
          type: "text",
          required: false,
          pdfRef: "Parent 2 Place of Birth",
          rect: { page: 6, x: 170.17, y: 599.24, w: 308.82, h: 22 },
        },
        {
          id: "parent2_sex",
          label: "Parent 2 - Sex",
          type: "radio",
          required: false,
          pdfRef: "Parent 2 Gender",
          rect: { page: 6, x: 493.24, y: 600.81, w: 8.64, h: 18.37 },
          options: [
            {
              id: "M",
              label: "M",
              rect: { page: 6, x: 493.24, y: 610.54, w: 8.31, h: 8.64 },
            },
            {
              id: "F",
              label: "F",
              rect: { page: 6, x: 493.24, y: 600.81, w: 8.64, h: 8.97 },
            },
          ],
        },
        {
          id: "parent2_us_citizen",
          label: "Parent 2 - U.S. Citizen?",
          type: "radio",
          required: false,
          pdfRef: "Parent 2 US Citizen",
          rect: { page: 6, x: 530.37, y: 599.5, w: 8.71, h: 17.87 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 530.37, y: 608.73, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 530.44, y: 599.5, w: 8.64, h: 8.64 },
            },
          ],
        },
      ],
    },

    {
      id: "marriage",
      title: "11. Marital History",
      fields: [
        {
          id: "ever_married",
          label: "Have you ever been married?",
          type: "radio",
          required: false,
          pdfRef: "Ever Married",
          rect: { page: 6, x: 171.86, y: 589.61, w: 43.62, h: 8.93 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 171.86, y: 589.9, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 206.84, y: 589.61, w: 8.64, h: 8.64 },
            },
          ],
        },
        {
          id: "spouse_name",
          label:
            "Full name of current or most recent spouse (Last, First and Middle)",
          type: "text",
          required: false,
          pdfRef:
            "Full Name of Current Spouse or Most Recent Spouse (Last, first, Middle)",
          rect: { page: 6, x: 28.27, y: 558.07, w: 292.21, h: 21.88 },
          showIf: { ever_married: "Yes" },
        },
        {
          id: "spouse_dob",
          label: "Spouse - Date of Birth (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Current Spouse Date of Birth",
          rect: { page: 6, x: 326.43, y: 557.47, w: 130.36, h: 22 },
          showIf: { ever_married: "Yes" },
        },
        {
          id: "spouse_birthplace",
          label: "Spouse - Place of Birth",
          type: "text",
          required: false,
          pdfRef: "Current Spouse Place of Birth",
          rect: { page: 6, x: 462.35, y: 556.41, w: 122.57, h: 23.48 },
          showIf: { ever_married: "Yes" },
        },
        {
          id: "spouse_us_citizen",
          label: "Spouse - U.S. Citizen?",
          type: "radio",
          required: false,
          pdfRef: "Spouse US Citizen",
          rect: { page: 6, x: 29.75, y: 535.57, w: 37.73, h: 8.71 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 29.75, y: 535.64, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 58.84, y: 535.57, w: 8.64, h: 8.64 },
            },
          ],
          showIf: { ever_married: "Yes" },
        },
        {
          id: "marriage_date",
          label: "Date of Marriage (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Date of Marriage (mm/dd/yyyy)",
          rect: { page: 6, x: 152.13, y: 533.58, w: 100.1, h: 22 },
          showIf: { ever_married: "Yes" },
        },
        {
          id: "widowed_divorced",
          label: "Have you ever been widowed or divorced?",
          type: "radio",
          required: false,
          pdfRef: "Divorced",
          rect: { page: 6, x: 308.08, y: 535.86, w: 43.84, h: 8.71 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 308.08, y: 535.93, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 343.28, y: 535.86, w: 8.64, h: 8.64 },
            },
          ],
          showIf: { ever_married: "Yes" },
        },
        {
          id: "widow_divorce_date",
          label: "Widow/Divorce Date (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Widow/Divorce Date (mm/dd/yyyy)",
          rect: { page: 6, x: 491.4, y: 533.67, w: 93.05, h: 22 },
          showIf: { ever_married: "Yes", widowed_divorced: "Yes" },
        },
      ],
    },

    {
      id: "contact-work",
      title: "12-14. Contact, Occupation and Employer",
      fields: [
        {
          id: "additional_phone",
          label: "12. Additional Contact Phone Number",
          type: "text",
          required: false,
          pdfRef: "Applicant Additional Contact Phone Numbers",
          rect: { page: 6, x: 28.33, y: 496.59, w: 143.63, h: 22.42 },
        },
        {
          id: "additional_phone_type",
          label: "Additional phone type",
          type: "radio",
          required: false,
          pdfRef: "Additional #",
          rect: { page: 6, x: 194.55, y: 499.43, w: 42.17, h: 18.6 },
          options: [
            {
              id: "Home",
              label: "Home",
              rect: { page: 6, x: 194.55, y: 509.39, w: 8.64, h: 8.64 },
            },
            {
              id: "Work",
              label: "Work",
              rect: { page: 6, x: 194.77, y: 499.79, w: 8.64, h: 8.64 },
            },
            {
              id: "Cell",
              label: "Cell",
              rect: { page: 6, x: 227.79, y: 508.44, w: 8.64, h: 8.64 },
            },
            {
              id: "Other",
              label: "Other",
              rect: { page: 6, x: 228.08, y: 499.43, w: 8.64, h: 8.64 },
            },
          ],
        },
        {
          id: "additional_phone_other",
          label: "Additional phone type (other)",
          type: "text",
          required: false,
          pdfRef: "Additional # Other",
          rect: { page: 6, x: 241.7, y: 501, w: 36, h: 10 },
          showIf: { additional_phone_type: "Other" },
        },
        {
          id: "occupation",
          label: "13. Occupation (if age 16 or older)",
          type: "text",
          required: false,
          pdfRef: "Occupation",
          rect: { page: 6, x: 281.73, y: 497.84, w: 141.49, h: 21.34 },
        },
        {
          id: "employer_school",
          label: "14. Employer or School (if applicable)",
          type: "text",
          required: false,
          pdfRef: "Employer or School",
          rect: { page: 6, x: 429.95, y: 498.48, w: 156.55, h: 21.35 },
        },
      ],
    },

    {
      id: "appearance-travel",
      title: "15-18. Physical Description and Travel Plans",
      fields: [
        {
          id: "height",
          label: "15. Height",
          type: "text",
          required: false,
          pdfRef: "Height",
          rect: { page: 6, x: 28.75, y: 456.21, w: 44.06, h: 21.35 },
          helpText: "Feet and inches, for example 5 ft 10 in.",
        },
        {
          id: "hair_color",
          label: "16. Hair Color",
          type: "text",
          required: false,
          pdfRef: "Hair Color",
          rect: { page: 6, x: 78.38, y: 456.66, w: 54.95, h: 21.34 },
        },
        {
          id: "eye_color",
          label: "17. Eye Color",
          type: "text",
          required: false,
          pdfRef: "Eye Color",
          rect: { page: 6, x: 140, y: 456.03, w: 51.82, h: 21.35 },
        },
        {
          id: "travel_departure",
          label: "18. Departure Date (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Travel Departure Date",
          rect: { page: 6, x: 200.15, y: 455.74, w: 100.62, h: 21.76 },
          helpText: "If you have no travel plans, write none.",
        },
        {
          id: "travel_return",
          label: "Return Date (MM/DD/YYYY)",
          type: "date",
          required: false,
          pdfRef: "Travel Return Date",
          rect: { page: 6, x: 306.84, y: 456.27, w: 99.12, h: 20.9 },
        },
        {
          id: "travel_countries",
          label: "Countries to be Visited",
          type: "text",
          required: false,
          pdfRef: "Countries to be visited",
          rect: { page: 6, x: 411.23, y: 456.32, w: 173.74, h: 21.11 },
        },
      ],
    },

    {
      id: "permanent-address",
      title: "19. Permanent Address",
      description:
        "Complete only if a P.O. Box is listed above, or if your residence differs from your mailing address. Do not list a P.O. Box here.",
      fields: [
        {
          id: "permanent_street",
          label: "Street/RFD # or URB",
          type: "text",
          required: false,
          pdfRef: "Permanent Address Street",
          rect: { page: 6, x: 28.42, y: 414.21, w: 476.79, h: 21.76 },
        },
        {
          id: "permanent_apt",
          label: "Apartment/Unit",
          type: "text",
          required: false,
          pdfRef: "Permanent Address Apartment/Unit",
          rect: { page: 6, x: 518.82, y: 412.81, w: 59.96, h: 23.07 },
        },
        {
          id: "permanent_city",
          label: "City",
          type: "text",
          required: false,
          pdfRef: "Permanent Address City",
          rect: { page: 6, x: 28.53, y: 378.78, w: 400.21, h: 22.42 },
        },
        {
          id: "permanent_state",
          label: "State",
          type: "text",
          required: false,
          pdfRef: "Permanent Address State",
          rect: { page: 6, x: 439.2, y: 378.44, w: 32.18, h: 22 },
          maxLength: 2,
        },
        {
          id: "permanent_zip",
          label: "Zip Code",
          type: "text",
          required: false,
          pdfRef: "Permanent Address Zip Code",
          rect: { page: 6, x: 490.09, y: 378.16, w: 95.67, h: 23.31 },
          maxLength: 6,
        },
      ],
    },

    {
      id: "emergency",
      title: "20. Emergency Contact",
      description:
        "Someone not traveling with you, to be contacted in the event of an emergency.",
      fields: [
        {
          id: "emergency_name",
          label: "Name",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact Name",
          rect: { page: 6, x: 26.31, y: 335.58, w: 225.45, h: 22.42 },
        },
        {
          id: "emergency_address",
          label: "Address: Street/RFD # or P.O. Box",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact Address",
          rect: { page: 6, x: 255.4, y: 334.92, w: 271.26, h: 22.42 },
        },
        {
          id: "emergency_apt",
          label: "Apartment/Unit",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact Apartment/Unit",
          rect: { page: 6, x: 532.99, y: 335.58, w: 54.61, h: 22.42 },
        },
        {
          id: "emergency_city",
          label: "City",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact City",
          rect: { page: 6, x: 26.7, y: 301, w: 190.1, h: 24.38 },
        },
        {
          id: "emergency_state",
          label: "State",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact State",
          rect: { page: 6, x: 220.19, y: 301.02, w: 25.05, h: 22.7 },
          maxLength: 2,
        },
        {
          id: "emergency_zip",
          label: "Zip Code",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact Zip Code",
          rect: { page: 6, x: 249.57, y: 301.27, w: 79.48, h: 22.42 },
          maxLength: 6,
        },
        {
          id: "emergency_phone",
          label: "Phone Number",
          type: "text",
          required: false,
          pdfRef: "Emergency Contact Phone",
          rect: { page: 6, x: 334.01, y: 301.54, w: 114.17, h: 22.42 },
        },
        {
          id: "emergency_relationship",
          label: "Relationship",
          type: "text",
          required: false,
          pdfRef: "Relationship to Applicant",
          rect: { page: 6, x: 451.5, y: 303.5, w: 132.5, h: 19.15 },
        },
      ],
    },

    {
      id: "prior-passport",
      title: "21. Previous U.S. Passport",
      fields: [
        {
          id: "ever_applied",
          label:
            "Have you ever applied for or been issued a U.S. Passport Book or Passport Card?",
          type: "radio",
          required: false,
          pdfRef: "Ever Applied or Issued",
          rect: { page: 6, x: 362.55, y: 291.35, w: 42.21, h: 9.15 },
          options: [
            {
              id: "Yes",
              label: "Yes",
              rect: { page: 6, x: 362.55, y: 291.86, w: 8.64, h: 8.64 },
            },
            {
              id: "No",
              label: "No",
              rect: { page: 6, x: 396.12, y: 291.35, w: 8.64, h: 8.64 },
            },
          ],
        },
        {
          id: "prior_book_name",
          label: "Name printed on your most recent book",
          type: "text",
          required: false,
          pdfRef:
            "Your name as printed on your most recent U.S. passport book and/or passport card",
          rect: { page: 6, x: 28.43, y: 257.18, w: 127.09, h: 22 },
          showIf: { ever_applied: "Yes" },
        },
        {
          id: "book_status",
          label: "Status of Book",
          type: "radio",
          required: false,
          pdfRef: "Book Status",
          rect: { page: 6, x: 159.19, y: 258.16, w: 64.73, h: 20.84 },
          options: [
            {
              id: "Submitting",
              label: "Submitting with application",
              rect: { page: 6, x: 159.19, y: 270.36, w: 8.64, h: 8.64 },
            },
            {
              id: "Stolen",
              label: "Stolen",
              rect: { page: 6, x: 159.19, y: 258.16, w: 8.64, h: 8.64 },
            },
            {
              id: "Lost",
              label: "Lost",
              rect: { page: 6, x: 189.45, y: 258.16, w: 8.64, h: 8.64 },
            },
            {
              id: "Possession",
              label: "In my possession (if expired)",
              rect: { page: 6, x: 215.28, y: 258.16, w: 8.64, h: 8.64 },
            },
          ],
          showIf: { ever_applied: "Yes" },
        },
        {
          id: "prior_card_name",
          label: "Name printed on your most recent card",
          type: "text",
          required: false,
          pdfRef: "Name as printed on your most recent passport card",
          rect: { page: 6, x: 310.91, y: 257, w: 119.54, h: 21.23 },
          showIf: { ever_applied: "Yes" },
        },
        {
          id: "card_status",
          label: "Status of Card",
          type: "radio",
          required: false,
          pdfRef: "Card Status",
          rect: { page: 6, x: 434.61, y: 257.12, w: 66.86, h: 19.4 },
          options: [
            {
              id: "Submitting",
              label: "Submitting with application",
              rect: { page: 6, x: 434.61, y: 267.88, w: 8.64, h: 8.64 },
            },
            {
              id: "Stolen",
              label: "Stolen",
              rect: { page: 6, x: 434.77, y: 257.12, w: 8.64, h: 8.64 },
            },
            {
              id: "Lost",
              label: "Lost",
              rect: { page: 6, x: 466.63, y: 257.12, w: 8.64, h: 8.64 },
            },
            {
              id: "Possession",
              label: "In my possession (if expired)",
              rect: { page: 6, x: 492.83, y: 257.12, w: 8.64, h: 8.64 },
            },
          ],
          showIf: { ever_applied: "Yes" },
        },
        {
          id: "loss_circumstances",
          label:
            "If your most recent book or card was lost or stolen, explain in detail",
          type: "text",
          required: false,
          pdfRef: "Circumstances of lost/stolen book/card",
          rect: { page: 6, x: 29.27, y: 197.19, w: 558.26, h: 35.36 },
          maxLength: 250,
          multiline: true,
          showIf: { ever_applied: "Yes" },
          helpText:
            "Include the previous book or card number, the date and location of the loss or theft, and whether you filed a police report.",
        },
      ],
    },
  ],
};
